// Code generated by `codex-core/src/bin/hooks_rust_sdk.rs`. DO NOT EDIT.
//
// This module is generated from the Rust hook payload schema (source-of-truth).
//
// Re-generate from the repo:
//   cd codex-rs
//   cargo run -p codex-core --bin hooks_rust_sdk --features hooks-schema --quiet \
//     > hooks-sdk/src/generated.rs

use serde::Deserialize;
use serde::Serialize;
use serde_json::Value;
use std::collections::BTreeMap;

pub type ExtraFields = BTreeMap<String, Value>;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum ApprovalKind {
    #[serde(rename = "apply-patch")]
    ApplyPatch,
    #[serde(rename = "elicitation")]
    Elicitation,
    #[serde(rename = "exec")]
    Exec,
    #[serde(other)]
    Unknown,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum AskForApproval {
    #[serde(rename = "never")]
    Never,
    #[serde(rename = "on-failure")]
    OnFailure,
    #[serde(rename = "on-request")]
    OnRequest,
    #[serde(rename = "untrusted")]
    Untrusted,
    #[serde(other)]
    Unknown,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum NetworkAccess {
    #[serde(rename = "enabled")]
    Enabled,
    #[serde(rename = "restricted")]
    Restricted,
    #[serde(other)]
    Unknown,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct TokenUsage {
    #[serde(rename = "cached_input_tokens")]
    pub cached_input_tokens: i64,
    #[serde(rename = "input_tokens")]
    pub input_tokens: i64,
    #[serde(rename = "output_tokens")]
    pub output_tokens: i64,
    #[serde(rename = "reasoning_output_tokens")]
    pub reasoning_output_tokens: i64,
    #[serde(rename = "total_tokens")]
    pub total_tokens: i64,
    #[serde(flatten)]
    pub extra: ExtraFields,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum ToolCallStatus {
    #[serde(rename = "aborted")]
    Aborted,
    #[serde(rename = "completed")]
    Completed,
    #[serde(other)]
    Unknown,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct AgentTurnCompletePayload {
    #[serde(rename = "cwd")]
    pub cwd: String,
    #[serde(rename = "event-id")]
    pub event_id: String,
    #[serde(rename = "input-messages")]
    pub input_messages: Vec<String>,
    #[serde(rename = "last-assistant-message")]
    pub last_assistant_message: Option<String>,
    #[serde(rename = "schema-version")]
    pub schema_version: u32,
    #[serde(rename = "thread-id")]
    pub thread_id: String,
    #[serde(rename = "timestamp")]
    pub timestamp: String,
    #[serde(rename = "turn-id")]
    pub turn_id: String,
    #[serde(rename = "type")]
    pub event_type: String,
    #[serde(flatten)]
    pub extra: ExtraFields,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ApprovalRequestedPayload {
    #[serde(rename = "approval-policy")]
    pub approval_policy: Option<AskForApproval>,
    #[serde(rename = "call-id")]
    pub call_id: Option<String>,
    #[serde(rename = "command")]
    pub command: Option<Vec<String>>,
    #[serde(rename = "cwd")]
    pub cwd: Option<String>,
    #[serde(rename = "event-id")]
    pub event_id: String,
    #[serde(rename = "grant-root")]
    pub grant_root: Option<String>,
    #[serde(rename = "kind")]
    pub kind: ApprovalKind,
    #[serde(rename = "message")]
    pub message: Option<String>,
    #[serde(rename = "paths")]
    pub paths: Option<Vec<String>>,
    #[serde(rename = "proposed-execpolicy-amendment")]
    pub proposed_execpolicy_amendment: Option<Vec<String>>,
    #[serde(rename = "reason")]
    pub reason: Option<String>,
    #[serde(rename = "request-id")]
    pub request_id: Option<String>,
    #[serde(rename = "sandbox-policy")]
    pub sandbox_policy: Option<Value>,
    #[serde(rename = "schema-version")]
    pub schema_version: u32,
    #[serde(rename = "server-name")]
    pub server_name: Option<String>,
    #[serde(rename = "thread-id")]
    pub thread_id: String,
    #[serde(rename = "timestamp")]
    pub timestamp: String,
    #[serde(rename = "turn-id")]
    pub turn_id: Option<String>,
    #[serde(rename = "type")]
    pub event_type: String,
    #[serde(flatten)]
    pub extra: ExtraFields,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ModelRequestStartedPayload {
    #[serde(rename = "attempt")]
    pub attempt: u32,
    #[serde(rename = "cwd")]
    pub cwd: String,
    #[serde(rename = "event-id")]
    pub event_id: String,
    #[serde(rename = "has-output-schema")]
    pub has_output_schema: bool,
    #[serde(rename = "model")]
    pub model: String,
    #[serde(rename = "model-request-id")]
    pub model_request_id: String,
    #[serde(rename = "parallel-tool-calls")]
    pub parallel_tool_calls: bool,
    #[serde(rename = "prompt-input-item-count")]
    pub prompt_input_item_count: u64,
    #[serde(rename = "provider")]
    pub provider: String,
    #[serde(rename = "schema-version")]
    pub schema_version: u32,
    #[serde(rename = "thread-id")]
    pub thread_id: String,
    #[serde(rename = "timestamp")]
    pub timestamp: String,
    #[serde(rename = "tool-count")]
    pub tool_count: u64,
    #[serde(rename = "turn-id")]
    pub turn_id: String,
    #[serde(rename = "type")]
    pub event_type: String,
    #[serde(flatten)]
    pub extra: ExtraFields,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ModelResponseCompletedPayload {
    #[serde(rename = "attempt")]
    pub attempt: u32,
    #[serde(rename = "cwd")]
    pub cwd: String,
    #[serde(rename = "event-id")]
    pub event_id: String,
    #[serde(rename = "model-request-id")]
    pub model_request_id: String,
    #[serde(rename = "needs-follow-up")]
    pub needs_follow_up: bool,
    #[serde(rename = "response-id")]
    pub response_id: String,
    #[serde(rename = "schema-version")]
    pub schema_version: u32,
    #[serde(rename = "thread-id")]
    pub thread_id: String,
    #[serde(rename = "timestamp")]
    pub timestamp: String,
    #[serde(rename = "token-usage")]
    pub token_usage: Option<TokenUsage>,
    #[serde(rename = "turn-id")]
    pub turn_id: String,
    #[serde(rename = "type")]
    pub event_type: String,
    #[serde(flatten)]
    pub extra: ExtraFields,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct SessionEndPayload {
    #[serde(rename = "cwd")]
    pub cwd: String,
    #[serde(rename = "event-id")]
    pub event_id: String,
    #[serde(rename = "schema-version")]
    pub schema_version: u32,
    #[serde(rename = "session-source")]
    pub session_source: String,
    #[serde(rename = "thread-id")]
    pub thread_id: String,
    #[serde(rename = "timestamp")]
    pub timestamp: String,
    #[serde(rename = "type")]
    pub event_type: String,
    #[serde(flatten)]
    pub extra: ExtraFields,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct SessionStartPayload {
    #[serde(rename = "cwd")]
    pub cwd: String,
    #[serde(rename = "event-id")]
    pub event_id: String,
    #[serde(rename = "schema-version")]
    pub schema_version: u32,
    #[serde(rename = "session-source")]
    pub session_source: String,
    #[serde(rename = "thread-id")]
    pub thread_id: String,
    #[serde(rename = "timestamp")]
    pub timestamp: String,
    #[serde(rename = "type")]
    pub event_type: String,
    #[serde(flatten)]
    pub extra: ExtraFields,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ToolCallFinishedPayload {
    #[serde(rename = "attempt")]
    pub attempt: u32,
    #[serde(rename = "call-id")]
    pub call_id: String,
    #[serde(rename = "cwd")]
    pub cwd: String,
    #[serde(rename = "duration-ms")]
    pub duration_ms: u64,
    #[serde(rename = "event-id")]
    pub event_id: String,
    #[serde(rename = "model-request-id")]
    pub model_request_id: String,
    #[serde(rename = "output-bytes")]
    pub output_bytes: u64,
    #[serde(rename = "output-preview")]
    pub output_preview: Option<String>,
    #[serde(rename = "schema-version")]
    pub schema_version: u32,
    #[serde(rename = "status")]
    pub status: ToolCallStatus,
    #[serde(rename = "success")]
    pub success: bool,
    #[serde(rename = "thread-id")]
    pub thread_id: String,
    #[serde(rename = "timestamp")]
    pub timestamp: String,
    #[serde(rename = "tool-name")]
    pub tool_name: String,
    #[serde(rename = "turn-id")]
    pub turn_id: String,
    #[serde(rename = "type")]
    pub event_type: String,
    #[serde(flatten)]
    pub extra: ExtraFields,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ToolCallStartedPayload {
    #[serde(rename = "attempt")]
    pub attempt: u32,
    #[serde(rename = "call-id")]
    pub call_id: String,
    #[serde(rename = "cwd")]
    pub cwd: String,
    #[serde(rename = "event-id")]
    pub event_id: String,
    #[serde(rename = "model-request-id")]
    pub model_request_id: String,
    #[serde(rename = "schema-version")]
    pub schema_version: u32,
    #[serde(rename = "thread-id")]
    pub thread_id: String,
    #[serde(rename = "timestamp")]
    pub timestamp: String,
    #[serde(rename = "tool-name")]
    pub tool_name: String,
    #[serde(rename = "turn-id")]
    pub turn_id: String,
    #[serde(rename = "type")]
    pub event_type: String,
    #[serde(flatten)]
    pub extra: ExtraFields,
}
