// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExclusionLayerCounts } from "./ExclusionLayerCounts";
import type { ExclusionSourceCounts } from "./ExclusionSourceCounts";
import type { ExclusionToolCount } from "./ExclusionToolCount";

export type ExclusionSummaryEvent = { total_redacted: number, total_blocked: number, layers: ExclusionLayerCounts, sources: ExclusionSourceCounts, per_tool: Array<ExclusionToolCount>, };
