// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExclusionCounts } from "./ExclusionCounts";

export type ExclusionLayerCounts = { layer1_input_guards: ExclusionCounts, layer2_output_sanitization: ExclusionCounts, layer3_send_firewall: ExclusionCounts, layer4_request_interceptor: ExclusionCounts, layer5_hook_sanitization: ExclusionCounts, };
