// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExclusionCounts } from "./ExclusionCounts";

export type ExclusionToolCount = { tool_name: string, counts: ExclusionCounts, };
