// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type HookProcessBeginEvent = { 
/**
 * Unique identifier for this hook process.
 */
hook_id: string, 
/**
 * Identifier for the originating hook payload event.
 */
payload_event_id: string, 
/**
 * Hook event type (e.g., `agent-turn-complete`, `approval-requested`).
 */
event_type: string, 
/**
 * The hook command that was spawned.
 */
command: Array<string>, };
