// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type HookProcessEndEvent = { 
/**
 * Unique identifier for the hook process that finished.
 */
hook_id: string, 
/**
 * Exit code if available.
 */
exit_code: number | null, };
