// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { McpAuthStatus } from "./McpAuthStatus";
import type { McpServerSnapshotState } from "./McpServerSnapshotState";
import type { Resource } from "./Resource";
import type { ResourceTemplate } from "./ResourceTemplate";
import type { Tool } from "./Tool";

export type McpListToolsResponseEvent = { 
/**
 * Fully qualified tool name -> tool definition.
 */
tools: { [key in string]?: Tool }, 
/**
 * Known resources grouped by server name.
 */
resources: { [key in string]?: Array<Resource> }, 
/**
 * Known resource templates grouped by server name.
 */
resource_templates: { [key in string]?: Array<ResourceTemplate> }, 
/**
 * Authentication status for each configured MCP server.
 */
auth_statuses: { [key in string]?: McpAuthStatus }, 
/**
 * Snapshot state for each MCP server (cached vs ready).
 */
server_states: { [key in string]?: McpServerSnapshotState }, };
