// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TokenUsage } from "./TokenUsage";

export type TokenUsageInfo = { total_token_usage: TokenUsage, last_token_usage: TokenUsage, model_context_window: number | null, 
/**
 * Full, unscaled model context window. When `model_context_window` reserves headroom,
 * this value retains the full window for display.
 */
full_model_context_window: number | null, };
